repos:
  - repo: https://github.com/vmnomad/pre-commit
    rev: "v0.0.2" # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-validate # It should be the first step as it runs terraform init required by tflint
      - id: tflint
        args:
          - "--config=__GIT_ROOT__/.tflint.hcl"

  - repo: local
    hooks:
      - id: terraform-fmt
        name: terraform fmt
        entry: terraform fmt -recursive
        language: system
        pass_filenames: false


  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.19.0" # Get the latest from: https://github.com/terraform-docs/terraform-docs/releases
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", ".", "--output-file", "README.md"]


  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "3.2.216" # Get the latest from: https://github.com/bridgecrewio/checkov/releases
    hooks:
      - id: checkov
        args: [--skip-check, "CKV_TF_1"] # Terraform module sources do not use a git url with a commit hash revision

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0" # Get the latest from: https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
      - id: mixed-line-ending
        args: ["--fix=no"]
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-yaml
